version: '3'

services:

  proxy:
    container_name: proxy
    image: httpd:2.4.57-alpine
    restart: always
    env_file: ./common.env
    environment:
      no_proxy: redmine,rocketchat,sonarqube,subversion
    ports:
      - "80:80"
    volumes:
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
    depends_on:
      - redmine
      - rocketchat
      - sonarqube
      - subversion
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  subversion:
    container_name: subversion
    restart: always
    env_file: ./common.env
    build:
      context: ./dockerfiles/subversion
      args:
        HTTP_PROXY: $HTTP_PROXY
        HTTPS_PROXY: $HTTPS_PROXY
        http_proxy: $http_proxy
        https_proxy: $https_proxy
    environment:
      - SVN_REPO=repo
    volumes:
      - /data/svn:/var/svn
      - ./svn/etc/apache2/conf.d:/etc/apache2/conf.d
      - /data/svn-davsvn-htpasswd:/etc/apache2/svn-davsvn-htpasswd

  redmine:
    container_name: redmine
    build:
      context: ./dockerfiles/redmine
    restart: always
    env_file: ./common.env
    environment:
      REDMINE_DB_POSTGRES: redmine-db
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: redmine
      REDMINE_RELATIVE_URL_ROOT: /redmine
    volumes:
      - /data/redmine-files:/usr/src/redmine/files
      - /data/redmine-plugins:/usr/src/redmine/plugins
    depends_on:
      - redmine-db
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  redmine-db:
    container_name: redmine-db
    image: postgres:15.3-alpine
    restart: always
    env_file: ./common.env
    environment:
      POSTGRES_USER: redmine
      POSTGRES_PASSWORD: redmine
    volumes:
      - /data/redmine-db:/var/lib/postgresql/data
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  rocketchat:
    container_name: rocketchat
    image: rocket.chat:5.4.9
    restart: always
    env_file: ./common.env
    environment:
      MONGO_URL: mongodb://rocketchat-db:27017/rocketchat?replicaSet=rs0&directConnection=true
      MONGO_OPLOG_URL: mongodb://rocketchat-db:27017/local?replicaSet=rs0&directConnection=true
      ROOT_URL: <ブラウザからrocketchatにアクセスする場合のURL>
    volumes:
      - /data/rocketchat:/app/uploads
    depends_on:
      - rocketchat-db
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  rocketchat-db:
    container_name: rocketchat-db
    image: mongo:5.0.25
    restart: always
    env_file: ./common.env
    command: mongod --oplogSize 128 --replSet rs0
    volumes:
      - /data/rocketchat-db:/data/db
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  # this container's job is just run the command to initialize the replica set.
  # it will run the command and remove himself (it will not stay running)
  mongo-init-replica:
    image: mongo:5.0.25
    command: 'bash -c "for i in `seq 1 30`; do mongosh rocketchat-db/rocketchat --eval \"rs.initiate({ _id: ''rs0'', members: [ { _id: 0, host: ''localhost:27017'' } ]})\" && s=$$? && break || s=$$?; echo \"Tried $$i times. Waiting 5 secs...\"; sleep 5; done; (exit $$s)"'
    depends_on:
      - rocketchat-db

  sonarqube:
    container_name: sonarqube
    image: sonarqube:10.1.0-community
    restart: always
    env_file: ./common.env
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonarqube-db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - ./sonar.properties:/opt/sonarqube/conf/sonar.properties
      - /data/sonarqube/data:/opt/sonarqube/data
      - /data/sonarqube/extensions:/opt/sonarqube/extensions
      - /data/sonarqube/bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    depends_on:
      - sonarqube-db
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  sonarqube-db:
    container_name: sonarqube-db
    image: postgres:15.3-alpine
    restart: always
    env_file: ./common.env
    environment:
      POSTGRES_DB: sonar
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - /data/sonarqube-db:/var/lib/postgresql/data
    logging:
      options:
        max-size: "10m"
        max-file: "10"
