# - 修正内容
#   - <と>で囲まれた部分を指定します。
#   - git-access-tokenはGitLabにアクセスして確認します。
#     - 作成したユーザでログイン＞画面右上の「プルダウン」＞「Settings」
#       ＞「Account」タブ＞「Private Tokens」＞「Private token」

git-username: <GitLabのユーザ名>
git-password: <GitLabのパスワード>
git-project-url: <GitLabのプロジェクトURL>

docker-repo-username: admin
docker-repo-password: admin123

sonar-url: <GitLabのユーザ名>

chat-webhook-url: <Rocket.ChatのWebHooKへのURL>

cf-api: <PCFのAPIへのURL>
cf-username: <PCFのユーザ名>
cf-password: <PCFのパスワード>
cf-org: <PCFの組織名>
