image: <CIサーバのIPアドレス>:19081/maven-jdk-17-with-sshpass-on-docker

stages:
  - build
  - deploy

variables:
  SONAR_HOST_URL: <SonarQubeのURL>
  SONAR_TOKEN: <SonarQubeのトークン>
  DEMO_HOST: <Demoサーバのホスト>
  DEMO_PORT: <DemoサーバのSSHのポート番号>
  DEMO_USERNAME: <DemoサーバのSSHのユーザ名>
  DEMO_PASSWORD: <DemoサーバのSSHのパスワード>

Build_Job:
  stage: build
  script:
    - mvn test -s ci/settings.xml
    - mvn sonar:sonar -Dsonar.host.url=http://${SONAR_HOST_URL}/sonarqube -Dsonar.token=${SONAR_TOKEN} -Dsonar.projectKey=${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME} -Dsonar.projectName=${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME} -s ci/settings.xml

Deploy_Job:
  stage: deploy
  only:
    - develop
  script:
    - mvn clean package -s ci/settings.xml
    - mkdir -p target/app
    - cp $(find target/ -name *.war) target/app/
    - cp ci/deploy-to-demo/* target/app/
    - ls -l target/app/
    - sshpass -p ${DEMO_PASSWORD} ssh -p ${DEMO_PORT} -oStrictHostKeyChecking=no ${DEMO_USERNAME}@${DEMO_HOST} "mkdir -p app"
    - sshpass -p ${DEMO_PASSWORD} ssh -p ${DEMO_PORT} -oStrictHostKeyChecking=no ${DEMO_USERNAME}@${DEMO_HOST} "cd app && rm -rf *"
    - sshpass -p ${DEMO_PASSWORD} scp -P ${DEMO_PORT} -oStrictHostKeyChecking=no -r target/app/ ${DEMO_USERNAME}@${DEMO_HOST}:~/
    - sshpass -p ${DEMO_PASSWORD} ssh -p ${DEMO_PORT} -oStrictHostKeyChecking=no ${DEMO_USERNAME}@${DEMO_HOST} "cd app && sh up.sh"

