version: '3'

services:

  proxy:
    container_name: proxy
    image: httpd:2.2.34-alpine
    restart: always
    env_file: ./common.env
    environment:
      no_proxy: concourse-web,gitlab,nexus.repository
    ports:
      - "80:80"
    volumes:
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
    depends_on:
      - concourse-web
      - gitlab
      - nexus.repository
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  concourse-worker:
    container_name: concourse-worker
    image: concourse/concourse:3.3.4
    restart: always
    command: worker
    privileged: true
    env_file: ./common.env
    environment:
      CONCOURSE_TSA_HOST: concourse-web
      CONCOURSE_GARDEN_NETWORK:
      no_proxy: proxy,nexus.repository
    volumes:
      - ./keys/worker:/concourse-keys
    depends_on:
      - concourse-web
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  concourse-web:
    container_name: concourse-web
    image: concourse/concourse:3.3.4
    restart: unless-stopped
    command: web
    env_file: ./common.env
    environment:
      CONCOURSE_POSTGRES_HOST: concourse-db
      CONCOURSE_POSTGRES_USER: concourse
      CONCOURSE_POSTGRES_PASSWORD: concourse
      CONCOURSE_POSTGRES_DATABASE: concourse
      # https://github.com/concourse/concourse/issues/942
      CONCOURSE_EXTERNAL_URL: <ブラウザからConcourseにアクセスする場合のURL>
      CONCOURSE_BASIC_AUTH_USERNAME: <ユーザ名>
      CONCOURSE_BASIC_AUTH_PASSWORD: <パスワード>
      CONCOURSE_NO_REALLY_I_DONT_WANT_ANY_AUTH:
    expose:
      - "8080"
    volumes:
      - ./keys/web:/concourse-keys
    depends_on:
      - concourse-db
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  concourse-db:
    container_name: concourse-db
    image: postgres:9.5.7-alpine
    restart: always
    env_file: ./common.env
    environment:
      POSTGRES_DB: concourse
      POSTGRES_USER: concourse
      POSTGRES_PASSWORD: concourse
    volumes:
      - /data/concourse-db:/var/lib/postgresql/data
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ce:9.4.5-ce.0
    restart: always
    volumes:
      - /data/gitlab/data:/var/opt/gitlab
      - /data/gitlab/config:/etc/gitlab
    depends_on:
      - gitlab-db
    env_file: ./common.env
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url '<ブラウザからGitLabにアクセスする場合のURL>'
        gitlab_rails['time_zone'] = 'Tokyo'
        gitlab_rails['db_adapter'] = 'postgresql'
        gitlab_rails['db_host'] = 'gitlab-db'
        gitlab_rails['db_port'] = 5432
        gitlab_rails['db_database'] = 'gitlab'
        gitlab_rails['db_username'] = 'gitlab'
        gitlab_rails['db_password'] = 'gitlab'
        gitlab_monitor['enable'] = false
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        nginx['proxy_set_headers'] = {
          "X-Forwarded-Proto" => "https",
          "X-Forwarded-Ssl" => "on"
        }
      no_proxy: proxy
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  gitlab-db:
    container_name: gitlab-db
    image: postgres:9.5.7-alpine
    restart: always
    env_file: ./common.env
    environment:
      POSTGRES_DB: gitlab
      POSTGRES_USER: gitlab
      POSTGRES_PASSWORD: gitlab
    volumes:
      - /data/gitlab-db:/var/lib/postgresql/data
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  nexus.repository:
    container_name: nexus.repository
    image: kiyohome/nexus-with-ssl:3.3.2
    restart: always
    env_file: ./common.env
    environment:
      NEXUS_CONTEXT: nexus
    ports:
      - "18081:18081"
      - "18443:18443"
    volumes:
      - /data/nexus:/nexus-data
    logging:
      options:
        max-size: "10m"
        max-file: "10"
